### ISSUE TITLE
Ricochet planks and blades issue

### ISSUE THREAD

**Issue by Fr0dech** [LambdaGaming/ricochet-source-2#12]
> Blade disk spawns upside-down, makes 180 degrees rotation and does not spin in yaw axis while flying.
> It's still possible to land on ricochet planks under pyramid pads without any resistance by them.
> It's possible to resist initial ricochet plank's force of dropping you off and after your resistance it doesn't try to drop you off again (if you move, this ricochet plank it'll try to drop you off again)

https://user-images.githubusercontent.com/85352886/171686824-3756b94c-ac44-448a-9d47-d4688884260b.mp4

.

**Comment by LambdaGaming** [comment]
I recompiled the map and that seems to have fixed the trigger_push brushes for the most part. I also added more trigger_push brushes to the outer bars below the pyramids since there were none there before. Let me know if you can still stand on them after this update.

As for the decap disc spawning upside-down, I think it's just a side effect of the method I'm using to prevent the discs from moving and rotating on the z-axis when they collide with something. I'm not too concerned about it since it doesn't really affect gameplay and it's not noticeable at full speed.
