### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Fr0dech** [LambdaGaming/ricochet-source-2#2]
- Kill feed not working (if it should rn)
- Arrow's bump stops player casually

**Comment by LambdaGaming** [comment]
Right now the kill feed should display but it won't tell you the killer. Is it not showing up at all for you?
Also, the bump on the arrows is a side effect of the map importing method. I'll try fixing it.

**Comment by LambdaGaming** [comment]
So there doesn't seem to be any easy way of replacing the existing platforms on rc_deathmatch with your prefab, since they are all combined into one mesh. If you figure this out feel free to make a pull request. Otherwise, I'm not gonna worry about it since the whole map needs reimported eventually anyway.

I'm gonna close this but you can reopen it if you are still having issues with the kill feed. For future reference, try to make separate issues for each bug. It makes it easier for me to keep track of them.
